using System.Reflection;

namespace LabbyTwo.Core;

/// <param name="Char">The emoji itself — what gets stored on the tab, connection or link.</param>
/// <param name="Name">Its Unicode name, which is what search matches on.</param>
public sealed record Emoji(string Char, string Name, string Group);

/// <summary>
/// Every emoji the picker offers, read once from an embedded table.
///
/// The table is generated by <c>docs/make-emoji-data.py</c> from Python's own Unicode
/// database rather than being hand-written or downloaded at runtime: it needs no network,
/// no package, and regenerating it after a Unicode update picks up whatever was added.
/// </summary>
public static class EmojiCatalog
{
    private const string ResourceName = "LabbyTwo.Core.emoji.tsv";

    private static readonly Lazy<IReadOnlyList<Emoji>> Loaded = new(Load);

    public static IReadOnlyList<Emoji> All => Loaded.Value;

    /// <summary>Group names in the order the picker should show them.</summary>
    public static IReadOnlyList<string> Groups { get; } =
        ["Smileys", "People", "Animals & nature", "Food & drink", "Travel & places",
         "Activities & objects", "Symbols", "Flags", "Other"];

    private static IReadOnlyList<Emoji> Load()
    {
        using var stream = typeof(EmojiCatalog).Assembly.GetManifestResourceStream(ResourceName);
        if (stream is null)
            return [];

        using var reader = new StreamReader(stream);
        var list = new List<Emoji>(2600);
        while (reader.ReadLine() is { } line)
        {
            if (line.Length == 0)
                continue;
            var parts = line.Split('\t');
            if (parts.Length == 3)
                list.Add(new Emoji(parts[0], parts[1], parts[2]));
        }
        return list;
    }

    public static IReadOnlyList<Emoji> InGroup(string group) =>
        [.. All.Where(e => string.Equals(e.Group, group, StringComparison.Ordinal))];

    /// <summary>
    /// Every term has to appear somewhere in the name, so "red car" finds the red car and
    /// not everything red plus everything with wheels. Pasting an emoji finds itself.
    /// </summary>
    public static IReadOnlyList<Emoji> Search(string? query, int limit = 300)
    {
        if (string.IsNullOrWhiteSpace(query))
            return [];

        var trimmed = query.Trim();
        var exact = All.Where(e => e.Char == trimmed).ToList();
        if (exact.Count > 0)
            return exact;

        var terms = trimmed.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return
        [
            .. All.Where(e => terms.All(term => e.Name.Contains(term, StringComparison.OrdinalIgnoreCase)))
                  .Take(limit)
        ];
    }
}
